---
title: "Coal Mining Effects"
author: "Peter Menzies"
date: "9/9/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(metafor)
```

```{r}
datrich <- read_csv(here("Gardner_et_al_data-KAR35vs02_onlyprimates_nospaces.csv"))

datrich <- datrich %>% 
  mutate(mean_diff = MeanvalueatHighFauna - MeanvalueatLowFauna) %>% 
  mutate(s_pooled = sqrt((((HighFaunaN - 1) * SDatHighFauna ^ 2) + ((LowFaunaN - 1) * SDatLowFauna ^ 2)) / 
                           ((HighFaunaN - 1) + (LowFaunaN - 1)))) %>% 
  mutate(umd_se = s_pooled * sqrt((1 / HighFaunaN) + (1 / LowFaunaN))) %>% 
  mutate(cohen_d = mean_diff / s_pooled) %>% 
  mutate(j = 1 - (3 / (4 * (HighFaunaN + LowFaunaN - 2) - 1))) %>% 
  mutate(g = cohen_d * j) %>% 
  mutate(g_se = sqrt(((HighFaunaN + LowFaunaN) / (HighFaunaN * LowFaunaN)) + ((g ^ 2) / (2 * (HighFaunaN + LowFaunaN))))) %>% 
  mutate(w = 1 / (g_se ^ 2)) %>% 
  mutate(gw = g * w) 

pooled_fixed_effect = sum(datrich$gw) / sum(datrich$w)
```

